### ISSUE TITLE
add logic of proxy gene selection from syntenic sets

### ISSUE THREAD

**Issue by joelb123** [legumeinfo/azulejo#122]

**Comment by adf-ncgr** [comment]
@joelb123 please update the description of this task based on our conversation this morning and also give me an estimate for when you'll have something to look at.

**Comment by joelb123** [comment]
Wrote the code to read the synteny families into broader homology families.

Initial set of glyma and glyma+glyso proxy genes look likely by COB tomorrow.  Will update mid-day tomorrow.

**Comment by adf-ncgr** [comment]
please commit the code or describe more fully what was implemented today following our discussion. I'm not sure I am relating the initial part of your comment to that conversation.

**Comment by adf-ncgr** [comment]
> Do any of the genomes in LIS have assembly statistics, either as quality scores or bulk stats?  Having the quality scores makes the proxy gene selection problem much less heuristic-driven.

you mean like BUSCO? I don't really want to introduce bulk stats at this point as a selection criterion.
per-gene quality metrics are possible but don't (and won't) exist homogeneously enough to be of use for us.

> I have a list of proposed heuristics for today, and another list of derived statistics I intend to add in later another day, but it's worth knowing the answer to this one first.

please propose your list ASAP.

**Comment by joelb123** [comment]
A commit just now implements the commands annotate-homology, dagchainer-synteny, and proxy-genes.  Only the first is finished, but the others implement the correct flow.  I'm working on filling in the rest. 

I expect to have proxy-genes running by the end of the day with 1-per-cluster selection heuristics that only scratch the surface of what's available.  I'm jumping to that next.

**Comment by adf-ncgr** [comment]
so what is the list of heuristics that will be implemented by end of day?

**Comment by joelb123** [comment]
Responded via email.

**Comment by joelb123** [comment]
I'm doing the selection by user preference and a simple heuristic of length selection today.

**Comment by joelb123** [comment]
Commit just now has the beginning of proxy gene selection, which works for the trivial case singletons. :)
Still some between dagchainer and usearch, it seems, but it isn't glaring.

253702 genes in glyma+glyso to be downselected.

**Comment by joelb123** [comment]
Here's what I will implement this morning for selecting the proxy gene within families.  The proxy is supposed to be a gene that looks like a modal value w.r.t. length and sequence, avoiding genes with sequencing/bioinformatics errors that result in truncated or spuriously-long sequences.

The test data set is 5 glyma+glyso.  There are 20K homology groups, with singletons dominating the group size distribution at 20%, and local peaks at 5 (6%), 10 (11%), and 15 (3%) and a long tail up to 645.

1. If the group is a singleton (20%), pass it along for now.
2. If the group is a doubleton (7%), select the longest.  If the sequences are the exact same length, use the preference list.
3. If the group contains three or more genes, choose from the following in order, with picks in preference order:
   a. If there are duplicate gene lengths, pick from among them. 
   b. If there are synteny sets, pick from among the lowest-variance set after rejecting length outliers.
   c. Pick the gene with length closest to modal length.

**Comment by adf-ncgr** [comment]
Thanks Joel, this is a good overview of the planned approach. I will say that the numbers you report for glyma+glyso seem to suggest that genes related by the recent(ish) whole genome duplication event are getting collapsed (giving a preponderance of groups of size 10 over groups of size 5, and giving total homology group number at approx half the number of genes in soybean). But we can discuss that further later as it should not impact the logic of the proxy gene selection (though it would have a significant impact on the results obtained from  applying the logic). Not sure I completely get 3b- it sounds like it may relate to the problem mentioned above but you can elucidate later today when we meet up.

**Comment by joelb123** [comment]
These numbers are with the homology selection at the lowest value that usearch permits, which in practice on this set is something like 70% homology in protein space.  If you want more homology clusters (I used the word "group" before, but I think "clusters" is the better term and I'm trying to use it consistently), then one can set a higher threshold for homology.  

For now the threshold doesn't matter except to make a person satisfied with the number of clusters he or she wants, but once we have the logic to nominate a second proxy gene from a homology cluster then the selection is done on the basis of less info.

**Comment by joelb123** [comment]
To document the outcome of a discussion with Andrew just now:

There will be a single proxy selection criterion, based on both length and genome preference list discussed below.

1. Singleton homology clusters are passed along as-is.
2. Any genes in a synteny set get down-selected to one proxy per synteny set.
3. Any genes not in a synteny set get passed along with a value indicating which of them would be the proxy gene.

The proxy selection criterion has a part based on length and a part based on a list of genome preferences.  The length-based selection is fed into the preference-based selection.  The length-based selection is the modal length, if a single modal value exists, and the median if it does not, with the reasoning being that errors in length are independent so the mode in some cases is more likely to be free of sequencing/bioinformatics errors.  Where the distribution is even in length, the median will be two values to be passed along to preference selection. The default list of genome preferences is in order of number of genes, but that can be overridden by user input.

**Comment by joelb123** [comment]
Implemented the logic above in the commit just now.

**Comment by adf-ncgr** [comment]
great, I will try to give it a run-through and see how it behaves on a dataset of interest. thanks!

**Comment by joelb123** [comment]
First pass at this finished, closing.
