### ISSUE TITLE
reproduce 0.9.18 results 

### ISSUE THREAD

**Issue by joelb123** [legumeinfo/azulejo#192]
Using glycine7 and the external homology from dagchainer_tool, verify that the current version produces the same results or justify differences.

**Comment by joelb123** [comment]
Not strictly necessary for, but would by helped by #194

**Comment by adf-ncgr** [comment]
I'll assign myself the remaining task of looking at these against the "gold standard".

**Comment by adf-ncgr** [comment]
OK, it looks like the results are indeed close enough to what we had seen previously (0.9.18) that we can consider this one closed.
